version: 2.1

orbs:
  android: circleci/android@2.1.0

jobs:
  build:
    executor:
      name: android/android-machine
      # Circle ci free plans
      resource_class: medium
      tag: 2023.07.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
            - v1-dependencies-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
